

language: node_js
node_js:
  - "lts/*"
  - "7"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

  before_install:
  - npm i -g npm@6.1.0
  
  cache: npm

